<a href="https://colab.research.google.com/github/Rahularc21/Machine-Learning/blob/main/Dataframes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import pandas as pd

**Creating DataFrames**

In [4]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}

In [5]:
df=pd.DataFrame(data)

In [6]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [7]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]

In [8]:
pd.DataFrame(data_list)  #column names ni aaye is baar...

       0   1         2      3
0   John  28  New York  65000
1   Anna  34     Paris  70000
2  Peter  29    Berlin  62000
3  Linda  42    London  85000

In [9]:
col=['Name','Age','City','Salary']

In [10]:
df2=pd.DataFrame(data_list,columns=col)

In [11]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

**Selection and Indexing of Columns**

In [12]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [13]:
df2['Name']

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: object

In [14]:
df2[['Name','City']]   #Multiple Columns

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

**Creating new Columns**

In [15]:
df2['Designation']=['teacher','doctor','Engineer','teacher']

In [16]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000     teacher
1   Anna   34     Paris   70000      doctor
2  Peter   29    Berlin   62000    Engineer
3  Linda   42    London   85000     teacher

**Removing Columns**

In [17]:
df2.drop("Designation",axis=1,inplace=True)    #axis=1 na likheege to rows me dekhegaa..... inplace for permanent changes...

In [18]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [19]:
df2.drop(['City','Salary'],axis=1)   #removing multiple columns...

    Name  Age
0   John   28
1   Anna   34
2  Peter   29
3  Linda   42

In [20]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

**Selecting Rows**

In [21]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [22]:
# df2[0]     error

In [23]:
df2.loc[[0,1]]  #for selecting rows

   Name  Age      City  Salary
0  John   28  New York   65000
1  Anna   34     Paris   70000

In [24]:
df2.iloc[[0,1]] #with indexes

   Name  Age      City  Salary
0  John   28  New York   65000
1  Anna   34     Paris   70000

**Selecting Subsets of Rows and Columns**

In [26]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [31]:
df2.loc[[0,1]][['City','Salary']]

       City  Salary
0  New York   65000
1     Paris   70000

In [33]:
df2.loc[[2,3]][['Name','Age']]

    Name  Age
2  Peter   29
3  Linda   42

**Conditional Selection**

In [34]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [40]:
#want to see those people whose age is above 30
df2[df2['Age']>30]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [39]:
#want to see those people whose age is above 30 and from paris
df2[(df2['Age']>30) & (df2['City']=='Paris')]

   Name  Age   City  Salary
1  Anna   34  Paris   70000