<a href="https://colab.research.google.com/github/Rahularc21/Machine-Learning/blob/main/featureExtractionPandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [80]:
import numpy as np
import pandas as pd

In [81]:
df=pd.read_csv(r'/content/anime.csv')   #reading csv files

In [82]:
df.head()  #top 5 rows

   Rank                                              Title  Score
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05

In [83]:
#make a new column for episode count
#make a new column for time stamp
#which anime has the highest score
#give me top 5 highest scoring anime
#which anime has the highest episode count
#animes with top 5 episode count
#which is the longest running anime

In [84]:
#make a new column for episode count
#title se episode count niklagee
df.loc[0]['Title']

'Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr 2009 - Jul 20103,218,472 membersManga StoreVolume 1€4.58Preview'

In [85]:
#extract 64 eps
def extractEpisodes(txt):
  data=''
  check=False
  for i in txt:
    if i==')':
      break
    if i=='(':
      check=True
      continue
    if(check==True):
      data += i
  return data

In [86]:
extractEpisodes(df.loc[0]['Title'])

'64 eps'

In [87]:
df['Title'].apply(extractEpisodes).head(2)   #feature extraction

0    64 eps
1    24 eps
Name: Title, dtype: object

In [88]:
df['Episodes']=df['Title'].apply(extractEpisodes)

In [89]:
df.head(2)

   Rank                                              Title  Score Episodes
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10   64 eps
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07   24 eps

In [90]:
df['Episodes']=df['Episodes'].str.replace(" eps","")  #extracting only count of episodes

In [91]:
df.head(2)

   Rank                                              Title  Score Episodes
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10       64
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07       24

In [92]:
df.loc[0]['Episodes']   #it is in string

'64'

In [93]:
df['Episodes']=df['Episodes'].astype(int)   #converting in int

In [94]:
df.loc[0]['Episodes']

np.int64(64)

In [95]:
#make a new column for time stamp

In [96]:
df.loc[0]['Title']

'Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr 2009 - Jul 20103,218,472 membersManga StoreVolume 1€4.58Preview'

In [97]:
# Apr 2009 - Jul 2010 extract this 18 letters after the bracket

In [98]:
def extractTimeStamp(txt):
  check=False
  data=""
  for i in range(len(txt)):
      if txt[i]==')':
        for j in range(i+1,i+20):
          data+=txt[j]
  return data

In [99]:
df['Title'].apply(extractTimeStamp).head(2)

0    Apr 2009 - Jul 2010
1    Apr 2011 - Sep 2011
Name: Title, dtype: object

In [100]:
df['TotalTime']=df['Title'].apply(extractTimeStamp)

In [101]:
df.head()

,Rank,Title,Score,Episodes,TotalTime
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019

In [102]:
#lets extract the total months from total time

def total_months(x):
    start, end = x.split(' - ')
    start = pd.to_datetime(start, format='%b %Y')
    end = pd.to_datetime(end, format='%b %Y')
    return (end.year - start.year) * 12 + (end.month - start.month) + 1

df['Months'] = df['TotalTime'].apply(total_months)

In [104]:
df.head()

,Rank,Title,Score,Episodes,TotalTime,Months
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010,16
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011,6
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022,3
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016,12
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019,4

In [105]:
#which anime has the highest score
#give me top 5 highest scoring anime
#which anime has the highest episode count
#animes with top 5 episode count
#which is the longest running anime

In [117]:
df[df['Score']==df['Score'].max()]

,Rank,Title,Score,Episodes,TotalTime,Months
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.1,64,Apr 2009 - Jul 2010,16

In [126]:
#give me top 5 highest scoring anime
df.sort_values(by='Score',ascending=False).head(5)

,Rank,Title,Score,Episodes,TotalTime,Months
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010,16
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011,6
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022,3
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016,12
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019,4

In [130]:
#which anime has the highest episode count
df[df['Episodes']==df['Episodes'].max()]

,Rank,Title,Score,Episodes,TotalTime,Months
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...",8.94,201,Apr 2006 - Mar 2010,48

In [131]:
#animes with top 5 episode count
df.sort_values(by='Episodes',ascending=False).head()

,Rank,Title,Score,Episodes,TotalTime,Months
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...",8.94,201,Apr 2006 - Mar 2010,48
7,8,Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...,9.04,148,Oct 2011 - Sep 2014,36
11,12,Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...,9.02,110,Jan 1988 - Mar 1997,111
42,43,Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...,8.76,75,Oct 2000 - Mar 2002,18
24,25,"MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...",8.87,74,Apr 2004 - Sep 2005,18

In [134]:
#which is the longest running anime
df[df['Months']==df['Months'].max()]

,Rank,Title,Score,Episodes,TotalTime,Months
11,12,Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...,9.02,110,Jan 1988 - Mar 1997,111