<a href="https://colab.research.google.com/github/Rahularc21/Machine-Learning/blob/main/PandasOperations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
import numpy as np
import pandas as pd

**DataFrames basic Operations**

In [24]:
df1 = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': [10, 20, 30, 40, 50],
    'C': [100, 200, 300, 400, 500]
})

In [25]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [26]:
df1.shape

(5, 3)

In [27]:
df1.columns

Index(['A', 'B', 'C'], dtype='object')

In [28]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [29]:
df1.describe()

              A          B           C
count  5.000000   5.000000    5.000000
mean   3.000000  30.000000  300.000000
std    1.581139  15.811388  158.113883
min    1.000000  10.000000  100.000000
25%    2.000000  20.000000  200.000000
50%    3.000000  30.000000  300.000000
75%    4.000000  40.000000  400.000000
max    5.000000  50.000000  500.000000

In [30]:
df1['A']+10

0    11
1    12
2    13
3    14
4    15
Name: A, dtype: int64

**Dataframes Applying functions**

In [31]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [32]:
df1['D']=df1['B'] **2

In [33]:
def square(x):
  return x**2

In [36]:
df1['E']=df1['B'].apply(square)    #applying functionss

In [37]:
df1

   A   B    C     D     E
0  1  10  100   100   100
1  2  20  200   400   400
2  3  30  300   900   900
3  4  40  400  1600  1600
4  5  50  500  2500  2500

In [38]:
df1['F']=df1['B'].apply(lambda x:x**2)

In [39]:
df1

   A   B    C     D     E     F
0  1  10  100   100   100   100
1  2  20  200   400   400   400
2  3  30  300   900   900   900
3  4  40  400  1600  1600  1600
4  5  50  500  2500  2500  2500