<a href="https://colab.research.google.com/github/Rahularc21/Machine-Learning/blob/main/Series.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Series:**

A Series is a one-dimensional labeled array capable of **holding any data type**.The axis labels are collectively called the index.

**Creating series: Ye vertically lgte haiii**

In [1]:
import numpy as np
import pandas as pd

In [10]:
labels=['a','b','c']
my_list=[10,20,30]
arr=np.array([10,20,30])
d={'a':10,2:20,3:30}

In [11]:
#creating series now

In [12]:
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

0 1 2 are labels or indices and 10 20 30 are data points..

In [13]:
pd.Series(my_list,index=labels)  #custom labels

a    10
b    20
c    30
dtype: int64

In [14]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [15]:
pd.Series(d)  #by default labels are keys

a    10
2    20
3    30
dtype: int64

**Ye jyada ni pucha jata kyoki series 1D hai sirf to multiple series data ko mila ke hum ek dataframe bnate**